'use client'

import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronDown, Clock3, MessageSquare, Send, X } from 'lucide-react'

type Project={id:string;name:string;client_name:string;client_email:string|null;delivery_status:string;client_message:string|null}
type Event={id:string;event_type:string;file_name:string|null;metadata:unknown;created_at:string}
type Detail={project:Project;activity:Event[]}
const statuses=[['in_progress','In progress'],['ready_for_review','Ready for review'],['changes_requested','Changes requested'],['approved','Approved'],['delivered','Delivered'],['archived','Archived']]
function label(v:string){return statuses.find(x=>x[0]===v)?.[1]||v.replaceAll('_',' ')}
function eventLabel(v:string){return v.replace(/^project\.|^delivery\.|^upload\.|^file\.|^folder\./,'').replaceAll('.',' ').replace(/(^|\s)\S/g,c=>c.toUpperCase())}
function json(url:string,init?:RequestInit){return fetch(url,init).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d})}

export default function AdminDelivery(){
 const [open,setOpen]=useState(false),[projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[status,setStatus]=useState('in_progress'),[message,setMessage]=useState(''),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
 async function loadProjects(){try{const d=await json('/api/admin/projects');setProjects(d.projects||[]);if(!selected&&d.projects?.[0])setSelected(d.projects[0].id)}catch{}}
 async function loadDetail(id:string){try{const d=await json(`/api/admin/projects/${id}`);setDetail(d);setStatus(d.project.delivery_status||'in_progress');setMessage(d.project.client_message||'')}catch(e){setError(e instanceof Error?e.message:'Unable to load delivery')}
 }
 useEffect(()=>{void loadProjects()},[]);useEffect(()=>{if(selected)void loadDetail(selected)},[selected])
 const visible=useMemo(()=>detail?.activity.filter(e=>!e.event_type.startsWith('notification.')).slice(0,30)||[],[detail])
 async function save(){if(!selected)return;setBusy(true);setError('');setNotice('');try{const d=await json(`/api/admin/projects/${selected}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({deliveryStatus:status,clientMessage:message||null})});setNotice(d.emailSent?'Saved and client notified.':'Saved.');await loadDetail(selected);await loadProjects()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 async function addComment(){if(!selected||!comment.trim())return;setBusy(true);setError('');setNotice('');try{const d=await json(`/api/admin/projects/${selected}/delivery`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({comment:comment.trim()})});setComment('');setNotice(d.emailSent?'Comment added and client notified.':'Comment added.');await loadDetail(selected)}catch(e){setError(e instanceof Error?e.message:'Unable to add comment')}finally{setBusy(false)}}
 return <><button className="admin-delivery-trigger" onClick={()=>setOpen(true)}><Clock3 size={14}/><span>Delivery intelligence</span></button>{open&&<div className="admin-delivery-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><aside className="admin-delivery-panel" role="dialog" aria-modal="true" aria-label="Delivery intelligence"><button className="admin-delivery-close" onClick={()=>setOpen(false)} aria-label="Close"><X size={17}/></button><div className="admin-delivery-kicker">V0.4 / DELIVERY INTELLIGENCE</div><h2>Delivery control.</h2><label className="admin-delivery-select">PROJECT<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.client_name}</option>)}</select></label>{detail&&<><div className="admin-delivery-meta"><span>{detail.project.client_email||'No client email'}</span><b className={status}>{label(status)}</b></div><div className="admin-delivery-fields"><label>Delivery state<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label><label>Project message<textarea value={message} maxLength={1000} onChange={e=>setMessage(e.target.value)} placeholder="Message shown at the top of the client workspace…"/></label><button disabled={busy} className="primary" onClick={()=>void save()}><Check size={14}/> Save delivery state</button></div><div className="admin-delivery-comment"><div><MessageSquare size={14}/><strong>Comment for client</strong></div><textarea value={comment} maxLength={2000} onChange={e=>setComment(e.target.value)} placeholder="Add a delivery note or review context…"/><button disabled={busy||!comment.trim()} onClick={()=>void addComment()}><Send size={13}/> Add comment</button></div>{notice&&<div className="admin-delivery-notice">{notice}</div>}{error&&<div className="admin-delivery-error">{error}</div>}<div className="admin-delivery-history"><span>ACTIVITY</span><strong>Delivery history</strong>{visible.map(e=>{const body=typeof (e.metadata as Record<string,unknown>|null)?.body==='string'?(e.metadata as Record<string,string>).body:null;return <article key={e.id}><i/><div><b>{e.file_name||eventLabel(e.event_type)}</b><small>{e.file_name?eventLabel(e.event_type):'Project event'} · {new Date(e.created_at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small>{body&&<p>{body}</p>}</div></article>})}</div></>}</aside></div>}</>
}
